#pragma once

#define START_ITERATIONS 8
#define MIN_ITERATIONS 1
#define MAX_ITERATIONS 16

#define SOLVER_THREADS 8

#define RENDERER_PRIMITIVE_CIRCLE_POINTS 64
#define RENDERER_PRIMITIVE_CIRCLE_RADIUS 5.f